### ISSUE TITLE
Settings of public repos can be visited and possibly changed by anyone

### ISSUE THREAD

**Issue by bartkamphorst** [repotag/repotag#6] opened 2015-08-30 15:21 UTC
Collaborators can be added and removed by anyone. Renaming of the repository fails.

**Comment by dometto** [comment] 2015-08-30 16:33
We need the same thing as [here](https://github.com/repotag/repotag/blob/master/app/controllers/users_controller.rb#L2-L4) and [here](https://github.com/repotag/repotag/blob/master/app/controllers/users_controller.rb#L17-L18) for Users.

I was thinking of abstracting the view and update settings specs for the user model into a shared example, so we can easily apply the same specs to the repo model. Perhaps we can even abstract the `#settings` and `#update_settings` controller actions.

**Comment by dometto** [comment] 2015-08-31 00:23
Authorization for RepositoriesController added in d4c7537ba073ddadf3110928d4d553c027b6a6b3.

Haven't spec'd renaming yet. I take it the problem is renaming fails even for the repo' s owner? Speaking of renaming, that should probably be a separate ability, as we probably don't want contributors to change the name of a repo they don't own. :)

**Comment by bartkamphorst** [comment] 2015-08-31 08:00
Nice!

> I take it the problem is renaming fails even for the repo' s owner?

No, it does work, but there's currently no notification/alert because the update is being done through a remote ajax call.

> renaming, that should probably be a separate ability

Definitely. :smile:

**Comment by dometto** [comment] 2015-08-31 09:02
> there's currently no notification/alert because the update is being done through a remote ajax call.

So I guess we need something like [this](http://stackoverflow.com/a/17434302).

**Comment by dometto** [comment] 2015-08-31 09:07
On the update privileges: come to think of it, are there _any_ repo attributes or settings that we want contributors to be able to change? We also don't want contributors toggling `public` etc. :) I guess that should all be up to the owner. So:
- owner `can :edit, :update`
- contributor `can :write` or `can :push` or something (needed to update files in the repo through the editor, grack, or gollum)

In due time, we can always implement more fine-grained authorization, and implement a super-collaborator role that can change _some_ things, like repo description.

**Comment by bartkamphorst** [comment] 2015-09-01 12:04
Agreed. Only owners can see and change repo settings.

**Comment by dometto** [comment] 2015-09-14 17:12
Fixed in https://github.com/repotag/repotag/commit/a52ea440151782adcee5ac613978b77f6d85bdda

**Closed as completed by dometto** 2015-09-14 17:12 UTC
